name: 'docker-build-and-push'
description: 'Docker build and push'
inputs:
  base-dir:
    description: 'Base directory'
    required: false
    default: './services'
  service-name:
    description: 'Service name'
    required: true
outputs:
  service-name:
    description: "Service name"
    value: ${{ steps.docker-build-and-push-config.outputs.service-name }}
  branch-name:
    description: "Branch name"
    value: ${{ steps.branch-specific-config.outputs.branch-name }}
  image-rev:
    description: "Docker image revision"
    value: ${{ steps.branch-specific-config.outputs.image-rev }}
  tf-workingdir:
    description: "Terraform working directory"
    value: ${{ steps.branch-specific-config.outputs.tf-workingdir }}
  tf-lockfile:
    description: "Terraform lockfile"
    value: ${{ steps.branch-specific-config.outputs.tf-lockfile }}
  docker-load:
    description: "Docker load"
    value: ${{ steps.branch-specific-config.outputs.docker-load }}
  docker-push:
    description: "Docker push"
    value: ${{ steps.branch-specific-config.outputs.docker-push }}

runs:
  using: "composite"
  steps:
    - name: Docker Build nnd Push Config
      id: docker-build-and-push-config
      run: |
        set -euxo pipefail

        SERVICE_NAME="${{ inputs.service-name }}"
        SERVICE_NAME_SANITIZED="${SERVICE_NAME//_/-}"

        echo "::set-output name=service-name::$(echo $SERVICE_NAME_SANITIZED)"
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.EXTERNAL_CI_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.EXTERNAL_CI_SECRET_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Branch specific config
      uses: ./.github/actions/branch-specific-config
      id: branch-specific-config
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.base-dir }}/${{ inputs.service-name }}
        load: ${{ steps.branch-specific-config.outputs.docker-load }}
        push: ${{ steps.branch-specific-config.outputs.docker-push }}
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ steps.docker-build-and-push-config.outputs.service-name }}:${{ steps.branch-specific-config.outputs.image-rev }}