name: 'commit-changes'
description: 'Commit changes to the GitHub repository'
inputs:
  github-token:
    description: 'GitHub token to commit with'
    required: true
  commit-message:
    description: 'Commit message'
    default: 'Committed automatically during workspace run'
    required: false
runs:
  using: "composite"
  steps:
    - uses: nick-fields/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 3
        retry_on: error
        command: |
          echo "$GITHUB_CONTEXT"
          git stash -u
          git checkout "${GITHUB_REF:11}"
          git pull
          git stash apply ||:
          git config --global user.name 'Devops Bot'
          git config --global user.email 'devops-bot@users.noreply.github.com'
          git remote set-url origin "git@github.com:${GITHUB_REPOSITORY}.git"



          git add -A
          git commit -am "${{ inputs.commit-message }}"
          git push ||:
