# File managed by Terraform
# Contents will be overwritten automatically
# To make changes edit the original template in internal-organization

name: 'openvpn-setup'
description: 'Setup OpenVPN'
inputs:
  openvpn-version:
    description: 'OpenVPN version to setup'
    required: false
    default: '2.4.7-1ubuntu2.20.04.2'
  openvpn-profile:
    description: 'OpenVPN profile (Must be base64-encoded)'
    required: true
outputs:
  openvpn-config:
    description: 'OpenVPN config file'
    value: ${{ steps.environment-setup.outputs.openvpn-config }}

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/write-file
      with:
        path: ./.github/workflows/install_openvpn.sh
        contents: |
          #!/bin/bash -e

          echo "# ----------------------------------------------------------"
          echo "# Installing OpenVPN"
          echo "# ----------------------------------------------------------"
          sudo apt-get update
          sudo apt-get autoclean --assume-yes
          sudo apt-get install --assume-yes --no-install-recommends openvpn=${{ inputs.openvpn-version }}
          echo "# *** END: Installing OpenVPN"
    - name: Environment setup
      id: environment-setup
      shell: bash
      run: |
        echo $OPENVPN_EXTERNAL_CI_PROFILE | base64 -d > ${{ runner.temp	}}/config.ovpn
        echo "::set-output name=openvpn-config::${{ runner.temp	}}/config.ovpn"
      env:
        OPENVPN_EXTERNAL_CI_PROFILE: ${{ inputs.openvpn-profile }}
    - uses: actions/cache@v2
      id: cache-apt
      with:
        path: ${{ runner.temp }}/cache-apt
        key: ${{ runner.os }}-cache-apt-openvpn-${{ inputs.openvpn-version }}
    - uses: airvzxf/cache-anything-new-action@v1.0.1
      with:
        script: install_openvpn.sh
        is_cached: ${{ steps.cache-apt.outputs.cache-hit }}
        cache: ${{ runner.temp }}/cache-apt
        snapshot: '/var/cache/apt/archives'

