name: 'openvpn-setup'
description: 'Setup OpenVPN'
inputs:
  openvpn-profile:
    description: 'OpenVPN profile (Must be base64-encoded)'
    required: true
outputs:
  openvpn-config:
    description: 'OpenVPN config file'
    value: ${{ steps.environment-setup.outputs.openvpn-config }}

runs:
  using: 'composite'
  steps:
    - name: Install OpenVPN
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --assume-yes --no-install-recommends openvpn
    - name: Environment setup
      id: environment-setup
      shell: bash
      run: |
        echo $OPENVPN_EXTERNAL_CI_PROFILE | base64 -d > ${{ runner.temp	}}/config.ovpn
        echo "::set-output name=openvpn-config::${{ runner.temp	}}/config.ovpn"
      env:
        OPENVPN_EXTERNAL_CI_PROFILE: ${{ inputs.openvpn-profile }}

