name: 'openvpn-kill'
description: 'Kill a running connection to an OpenVPN server'
inputs:
  openvpn-log:
    description: 'OpenVPN log file to upload'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Kill VPN connection
      shell: bash
      run: |
        sudo touch ${{ inputs.openvpn-log }}
        sudo chmod 777 ${{ inputs.openvpn-log }}
        sudo killall openvpn
    - name: Upload VPN logs
      uses: actions/upload-artifact@v2
      with:
        name: VPN logs
        path: ${{ inputs.openvpn-log }}
