# File managed by Terraform
# Contents will be overwritten automatically
# To make changes edit the original template in internal-organization

name: 'openvpn-connect'
description: 'Connect to an OpenVPN server using a config file'
inputs:
  openvpn-version:
    description: 'OpenVPN version to setup'
    required: false
    default: '2.4.7-1ubuntu2.20.04.2'
  openvpn-profile:
    description: 'OpenVPN profile (Must be base64-encoded)'
    required: true
outputs:
  openvpn-config:
    description: 'OpenVPN config file'
    value: ${{ steps.setup-openvpn.outputs.openvpn-config }}
  openvpn-log:
    description: 'OpenVPN log file'
    value: ${{ steps.run-openvpn.outputs.openvpn-log }}

runs:
  using: 'composite'
  steps:
    - name: Setup OpenVPN
      uses: ./.github/actions/openvpn-setup
      id: setup-openvpn
      with:
        openvpn-profile: ${{ inputs.openvpn-profile }}
    - name: Connect to VPN Server
      shell: bash
      id: run-openvpn
      run: |
        sudo openvpn --config ${{ steps.setup-openvpn.outputs.openvpn-config }} --log "$(pwd)/vpn.log" --daemon
        echo "::set-output name=openvpn-log::$(pwd)/vpn.log"

